### ISSUE TITLE
lib and app folder are empty

### ISSUE THREAD

**Issue by pflegende** [MircoT/js-pdp8#24]
Great project!
we want show it on our retro night in Erfurt on Jun. 10th.

But I think I do something wrong in calling the github folder.
Everytime I open it - it's a empty page:

![MircoT_2023-05-27_132828_github com](https://github.com/MircoT/js-pdp8/assets/52720420/5c453a0a-0e4d-4b51-82e5-aaf603effc5e)

May be you have some suggestion how to work around.
CU

😄

**Comment by pflegende** [comment]
it seems, that opera, the used browser has a problem rendering gh at the moment.
excuse me!

I close the issue.

**Comment by MircoT** [comment]
> it seems, that opera, the used browser has a problem rendering gh at the moment. excuse me!
> 
> I close the issue.

Don't know if you already checked the original project too: [py-pdp8-tk](https://github.com/MircoT/py-pdp8-tk).
However, take into account that such projects are oriented to teaching.
